bump_version: null
lint:
  actions_ci: false
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - conf/modules/modules.config
  files_unchanged:
    - .gitignore
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/nf-core-fastquorum_logo_light.png
    - docs/images/Fulcrum.svg
  template_strings: false
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Nils Homer
  description: fgbio Best Practices FASTQ to Consensus Pipeline
  force: false
  is_nfcore: true
  name: fastquorum
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.2dev
update: null
