contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #fastquorum channel"
    url: https://nfcore.slack.com/channels/fastquorum
    about: Discussion about the nf-core/fastquorum pipeline
